export type Conference = {
  startDate: Date;
  endDate: Date;
  title: string;
  location: 'Online' | string;
  link: string;
  isPartner?: boolean;
  type: Array<'online' | 'in-person'>;
};

export const conferences: Conference[] = [
  {
    title: 'World Usability Day (WUD) Estonia',
    startDate: new Date('16 February 2026'),
    endDate: new Date('20 February 2026'),
    location: 'Tallinn, Estonia',
    type: ['in-person'],
    link: 'https://wud.ee/',
  },
  {
    title: 'Growing in Content',
    startDate: new Date('28 April 2026'),
    endDate: new Date('30 April 2026'),
    location: 'Online',
    type: ['online'],
    link: 'https://workingincontent.com/growing',
  },
  {
    title: 'UX Writer Conference',
    startDate: new Date('24 March 2026'),
    endDate: new Date('24 March 2026'),
    location: 'Online',
    type: ['online'],
    link: 'https://uxwriterconference.com',
  },
  {
    title: 'DITA-OT Day',
    startDate: new Date('1 Feb 2026'),
    endDate: new Date('1 Feb 2026'),
    location: 'Bruksela, Belgia',
    type: ['in-person'],
    link: 'https://www.oxygenxml.com/events/2026/dita-ot_day.html',
  },
  {
    title: 'DITA Europe',
    startDate: new Date('2 Feb 2026'),
    endDate: new Date('3 Feb 2026'),
    location: 'Bruksela, Belgia',
    type: ['in-person'],
    link: 'https://ditaeurope.infomanagementcenter.com',
  },
  {
    title: 'UX360 virtual',
    startDate: new Date('4 Feb 2026'),
    endDate: new Date('5 Feb 2026'),
    location: 'Online',
    type: ['online'],
    link: 'https://www.virtual.ux360summit.com/',
  },
  {
    title: 'Web Summit Qatar',
    startDate: new Date('1 Feb 2026'),
    endDate: new Date('4 Feb 2026'),
    location: 'Doha, Katar',
    type: ['in-person'],
    link: 'https://qatar.websummit.com',
  },
  {
    title: 'Nordic TechKomm',
    startDate: new Date('19 Mar 2026'),
    endDate: new Date('20 Mar 2026'),
    location: 'Sztokholm, Szwecja',
    type: ['in-person'],
    link: 'https://se.nordic-techkomm.com',
  },
  {
    title: 'Women TechStyle Summit',
    startDate: new Date('26 Mar 2026'),
    endDate: new Date('26 Mar 2026'),
    location: 'Online',
    type: ['online'],
    link: 'https://womentechstyle.pl/',
  },
  {
    title: 'Information Energy',
    startDate: new Date('22 April 2026'),
    endDate: new Date('24 April 2026'),
    location: 'Online',
    type: ['online'],
    link: 'https://www.informationenergy.org/',
  },
  {
    title: 'Learning Technologies',
    startDate: new Date('29 April 2026'),
    endDate: new Date('30 April 2026'),
    location: 'Londyn, Anglia',
    type: ['in-person'],
    link: 'https://www.learningtechnologies.co.uk',
  },
  {
    title: 'Web Summit Rio',
    startDate: new Date('8 June 2026'),
    endDate: new Date('11 June 2026'),
    location: 'Rio De Janeiro, Brazylia',
    type: ['in-person'],
    link: 'https://rio.websummit.com',
  },
  {
    title: 'Write The Docs',
    startDate: new Date('3 May 2026'),
    endDate: new Date('5 May 2026'),
    location: 'Portland, USA',
    type: ['in-person'],
    link: 'https://www.writethedocs.org/conf/portland/2026/',
  },
  {
    title: 'DDX Innovation & UX Conference',
    startDate: new Date('9 May 2026'),
    endDate: new Date('9 May 2026'),
    location: 'Monachium, Niemcy',
    type: ['in-person'],
    link: 'https://www.ddxconference.com/munich',
  },
  {
    title: 'UXDX USA',
    startDate: new Date('11 May 2026'),
    endDate: new Date('13 May 2026'),
    location: 'Nowy Jork, USA i online',
    type: ['in-person', 'online'],
    link: 'https://uxdx.com/usa/2026/',
  },
  {
    title: 'UX360 Europe',
    startDate: new Date('23 June 2026'),
    endDate: new Date('24 June 2026'),
    location: 'Berlin, Niemcy',
    type: ['in-person'],
    link: 'https://www.eu.ux360summit.com/',
  },
  {
    title: 'UX LX',
    startDate: new Date('12 May 2026'),
    endDate: new Date('15 May 2026'),
    location: 'Lizbona, Portugalia',
    type: ['in-person'],
    link: 'https://www.ux-lx.com',
  },
  {
    title: 'Evolution of TC',
    startDate: new Date('2 June 2026'),
    endDate: new Date('3 June 2026'),
    location: 'Sofia, Bułgaria',
    type: ['in-person'],
    link: 'https://evolution-of-tc.com',
  },
  {
    title: 'LocWorld55',
    startDate: new Date('9 June 2026'),
    endDate: new Date('11 June 2026'),
    location: 'Dublin, Irlandia',
    type: ['in-person'],
    link: 'https://locworld.com/events/locworld53-malmo-2026/',
  },
  {
    title: 'AGILE Conference',
    startDate: new Date('16 June 2026'),
    endDate: new Date('19 June 2026'),
    location: 'Tartu, Estonia',
    type: ['in-person'],
    link: 'https://agile-gi.eu/conference-2026',
  },
  {
    title: 'UX Scotland',
    startDate: new Date('10 June 2026'),
    endDate: new Date('12 June 2026'),
    location: 'Edynburg, Szkocja',
    type: ['in-person'],
    link: 'https://uxscotland.net/',
  },
  {
    title: 'Balisage: The Markup Conference',
    startDate: new Date('3 August 2026'),
    endDate: new Date('7 August 2026'),
    location: 'Online',
    type: ['online'],
    link: 'https://www.balisage.net/index.html',
  },
  {
    title: 'World Usability Congress',
    startDate: new Date('13 Oct 2026'),
    endDate: new Date('15 Oct 2026'),
    location: 'Graz, Austria',
    type: ['in-person'],
    link: 'https://worldusabilitycongress.com',
  },
  {
    title: 'KMIS',
    startDate: new Date('28 Oct 2026'),
    endDate: new Date('30 Oct 2026'),
    location: 'Angers, Francja',
    type: ['in-person'],
    link: 'https://kmis.scitevents.org',
  },
  {
    title: 'Leading Design London',
    startDate: new Date('11 Nov 2026'),
    endDate: new Date('12 Nov 2026'),
    location: 'Londyn, Anglia',
    type: ['in-person'],
    link: 'https://leadingdesign.com/conferences/london-2026',
  },
];
