export type Conference = {
  startDate: Date;
  endDate: Date;
  title: string;
  location: 'Online' | string;
  link: string;
  isPartner?: boolean;
  type: Array<'online' | 'in-person'>;
};

export const conferences: Conference[] = [
  {
    title: 'Konferencja Tłumaczy',
    startDate: new Date('26 September 2025'),
    endDate: new Date('27 September 2025'),
    location: 'Warszawa, Polska',
    type: ['in-person', 'online'],
    link: 'https://konferencja-tlumaczy.pl/',
    isPartner: true,
  },
  {
    title: 'Write The Docs Berlin',
    startDate: new Date('27 Oct 2025'),
    endDate: new Date('28 Oct 2025'),
    location: 'Berlin, Niemcy',
    type: ['in-person', 'online'],
    link: 'https://www.writethedocs.org/conf/berlin/2025/news/welcome/',
  },
  {
    title: 'UX Writer Conference',
    startDate: new Date('28 Jan 2025'),
    endDate: new Date('28 Jan 2025'),
    location: 'Online',
    type: ['online'],
    link: 'https://uxwriterconference.com',
  },
  {
    title: 'MEGAComm',
    startDate: new Date('12 Feb 2025'),
    endDate: new Date('13 Feb 2025'),
    location: 'Online and Israel',
    type: ['in-person', 'online'],
    link: 'https://megacomm.org/',
  },
  {
    title: 'DITA-OT Day',
    startDate: new Date('16 Feb 2025'),
    endDate: new Date('16 Feb 2025'),
    location: 'Kopenhaga, Dania',
    type: ['in-person'],
    link: 'https://www.oxygenxml.com/events/2025/dita-ot_day.html',
  },
  {
    title: 'DITA Europe',
    startDate: new Date('17 Feb 2025'),
    endDate: new Date('18 Feb 2025'),
    location: 'Kopenhaga, Dania',
    type: ['in-person'],
    link: 'https://ditaeurope.infomanagementcenter.com',
  },
  {
    title: 'UX360 virtual',
    startDate: new Date('19 Feb 2025'),
    endDate: new Date('20 Feb 2025'),
    location: 'Online',
    type: ['online'],
    link: 'https://www.virtual.ux360summit.com/',
  },
  {
    title: 'Web Summit Qatar',
    startDate: new Date('23 Feb 2025'),
    endDate: new Date('26 Feb 2025'),
    location: 'Doha, Katar',
    type: ['in-person'],
    link: 'https://qatar.websummit.com',
  },
  {
    title: 'Nordic TechKomm',
    startDate: new Date('12 Mar 2025'),
    endDate: new Date('13 Mar 2025'),
    location: 'Sztokholm, Szwecja',
    type: ['in-person'],
    link: 'https://se.nordic-techkomm.com',
  },
  {
    title: 'Women TechStyle Summit',
    startDate: new Date('20 Mar 2025'),
    endDate: new Date('20 Mar 2025'),
    location: 'Online',
    type: ['online'],
    link: 'https://womentechstyle.pl/',
  },
  {
    title: 'Leading Design New York',
    startDate: new Date('27 Mar 2025'),
    endDate: new Date('27 Mar 2025'),
    location: 'Nowy Jork, USA',
    type: ['in-person'],
    link: 'https://leadingdesign.com/conferences/leading-design-new-york-2025',
  },
  {
    title: 'Information Energy',
    startDate: new Date('2 April 2025'),
    endDate: new Date('4 April 2025'),
    location: 'Online',
    type: ['online'],
    link: 'https://www.informationenergy.org/de/',
  },
  {
    title: 'Learning Technologies',
    startDate: new Date('23 April 2025'),
    endDate: new Date('23 April 2025'),
    location: 'Londyn, Anglia',
    type: ['in-person'],
    link: 'https://www.learningtechnologies.co.uk',
  },
  {
    title: 'Web Summit Rio',
    startDate: new Date('27 April 2025'),
    endDate: new Date('30 April 2025'),
    location: 'Rio De Janeiro, Brazylia',
    type: ['in-person'],
    link: 'https://rio.websummit.com',
  },
  {
    title: 'Write The Docs',
    startDate: new Date('4 May 2025'),
    endDate: new Date('6 May 2025'),
    location: 'Portland, USA',
    type: ['in-person'],
    link: 'https://www.writethedocs.org/conf/portland/2025/',
  },
  {
    title: 'DDX Innovation & UX Conference',
    startDate: new Date('10 May 2025'),
    endDate: new Date('10 May 2025'),
    location: 'Monachium, Niemcy',
    type: ['in-person'],
    link: 'https://www.ddxconference.com/munich',
  },
  {
    title: 'UXDX USA',
    startDate: new Date('12 May 2025'),
    endDate: new Date('14 May 2025'),
    location: 'Nowy Jork, USA i online',
    type: ['in-person', 'online'],
    link: 'https://uxdx.com/usa/2025/',
  },
  {
    title: 'UX360 Europe',
    startDate: new Date('14 May 2025'),
    endDate: new Date('15 May 2025'),
    location: 'Berlin, Niemcy',
    type: ['in-person'],
    link: 'https://www.eu.ux360summit.com/',
  },
  {
    title: 'UXDX EMEA',
    startDate: new Date('19 May 2025'),
    endDate: new Date('21 May 2025'),
    location: 'Berlin, Niemcy i online',
    type: ['in-person'],
    link: 'https://uxdx.com/berlin/2025/',
  },
  {
    title: 'UX LX',
    startDate: new Date('20 May 2025'),
    endDate: new Date('23 May 2025'),
    location: 'Lizbona, Portugalia',
    type: ['in-person'],
    link: 'https://www.ux-lx.com',
  },
  {
    title: 'Evolution of TC',
    startDate: new Date('27 May 2025'),
    endDate: new Date('28 May 2025'),
    location: 'Sofia, Bułgaria',
    type: ['in-person'],
    link: 'https://evolution-of-tc.com',
  },
  {
    title: 'Web Summit Vancouver',
    startDate: new Date('27 May 2025'),
    endDate: new Date('30 May 2025'),
    location: 'Vancouver, Kanada',
    type: ['in-person'],
    link: 'https://vancouver.websummit.com',
  },
  {
    title: 'LocWorld53',
    startDate: new Date('3 June 2025'),
    endDate: new Date('5 June 2025'),
    location: 'Malmo, Szwecja',
    type: ['in-person'],
    link: 'https://locworld.com/events/locworld53-malmo-2025/',
  },
  {
    title: 'Markup UK',
    startDate: new Date('5 June 2025'),
    endDate: new Date('7 June 2025'),
    location: 'Londyn, Anglia',
    type: ['in-person'],
    link: 'https://markupuk.org/index.html',
  },
  {
    title: 'AGILE Conference',
    startDate: new Date('10 June 2025'),
    endDate: new Date('13 June 2025'),
    location: 'Drezno, Niemcy',
    type: ['in-person'],
    link: 'https://agile-gi.eu/conference-2025',
  },
  {
    title: 'UX Scotland',
    startDate: new Date('11 June 2025'),
    endDate: new Date('12 June 2025'),
    location: 'Edynburg, Szkocja',
    type: ['in-person'],
    link: 'https://uxscotland.net/',
  },
  {
    title: 'Balisage: The Markup Conference',
    startDate: new Date('4 August 2025'),
    endDate: new Date('8 August 2025'),
    location: 'Online',
    type: ['online'],
    link: 'https://www.balisage.net/index.html',
  },
  {
    title: 'CAKE conf',
    startDate: new Date(' 19 Sep 2025'),
    endDate: new Date(' 20 Sep 2025'),
    location: 'Kraków, Polska',
    type: ['in-person'],
    link: 'https://cakeconf.contentbytes.pl/',
    isPartner: true,
  },
  {
    title: 'World Usability Congress',
    startDate: new Date('14 Oct 2025'),
    endDate: new Date('16 Oct 2025'),
    location: 'Graz, Austria',
    type: ['in-person'],
    link: 'https://worldusabilitycongress.com',
  },
  {
    title: 'KMIS',
    startDate: new Date('20 Oct 2025'),
    endDate: new Date('22 Oct 2025'),
    location: 'Marbella, Hiszpania',
    type: ['in-person'],
    link: 'https://kmis.scitevents.org',
  },
  {
    title: 'tcworld conference',
    startDate: new Date('11 Nov 2025'),
    endDate: new Date('13 Nov 2025'),
    location: 'Stuttgart, Niemcy',
    type: ['in-person'],
    link: 'https://tcworldconference.tekom.de',
  },
  {
    title: 'Leading Design London',
    startDate: new Date('12 Nov 2025'),
    endDate: new Date('13 Nov 2025'),
    location: 'Londyn, Anglia',
    type: ['in-person'],
    link: 'https://leadingdesign.com/conferences/london-2025',
  },
  {
    title: 'Code Europe',
    startDate: new Date('30 June 2025'),
    endDate: new Date('1 July 2025'),
    location: 'Kraków, Polska',
    type: ['in-person'],
    link: 'https://www.codeeurope.pl',
    isPartner: true,
  },
  {
    title: 'TCUK',
    startDate: new Date('24 Nov 2025'),
    endDate: new Date('25 Nov 2025'),
    location: 'East Midlands Airport, Anglia',
    type: ['in-person'],
    link: 'https://istc.org.uk/tcuk/',
  },
];
